version: "3"
services:
  db:
    image: mysql:8.0
    container_name: laravel_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_ja_0900_as_cs

  php:
    build:
      context: ./docker/php/
    container_name: laravel_web
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
    links:
      - db
